services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
